# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Benjamin Tan
title: Senior Assistant Director
email: bentanjob90@gmail.com
website: www.github.com/OoStellarnightoO

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: ben_mars56
github_username:  OoStellarnightoO
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: benjamin-tan-analystsg
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile pic_github.png
about_content: | # this will include new lines to allow paragraphs
  Benjamin here. Happy for you to visit. Currently a Trade Officer with the Ministry of Trade and Industry. My main portfolio is Saudi Arabia and the Gulf Cooperation Council.
  I like to constantly explore new avenues of knowledge and am willing to take risks to jump into new areas. Currently looking to enter the pentesting/red teaming world. Am also open to exploring OSINT and Threat Intelligence paths given my intelligence background.

  
  Taking pentesting courses from TCM Academy with the aim of taking the PNPT certification by early next year. 
  I have taken courses on python and javascript though it has been sometime since i used both.


  Starting a personal pet project next year where I hope to do deep research into the Japanese Occupation of Singapore with a specific focus on the human experience from both the Japanese soldier and the local citizenry and trying to understand what would drive someone to be an informant and betray their own people

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: New Projects Cooking
        link: github.com/OoStellarnightoO
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Basic Apps to practice my Python and Rust Skills
        description: | # this will include new lines to allow paragraphs
          I will be developing a simple python/rust based tool to run checks against low-hanging fruits such as readable etc/shadow, elevated privileges etc. Akan Datang as I have been very busy with my main job for the last six months but now with a bit of time, I am going full steam. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ministry of Trade and Industry, Singapore
        link: https://www.mti.gov.sg/
        # link_text: 
        sub_title: Senior Assistant Director/Emerging Markets Division
        caption: November 2022 - Present
        quote: >
          Advancing Bilateral Trade and Economic ties between Singapore and the Middle East
        description: | # this will include new lines to allow paragraphs
            I am the main officer in charge engaging Saudi Arabia to enhance bilateral trade and economic ties. I was deeply involved in the successful conduct of the 3rd Saudi Arabia-Singapore Joint Committee that was held in Riyadh in October 2023 which saw seven MOUs signed. This was possible due to me and my team's consistent
            engagement of our Saudi counterparts throughout the year and working across with other stakeholders such as EnterpriseSG. I was also the staff officer in charge of staffing the Minister for various foreign delegation visits from Saudi Minister of Commerce, Dr Majid Al Qasabi to Oman's Minister
            of commerce, industry and investment promotion, Qais Al Yousef. Aside from the above, I have also planned two working level visits to Saudi Arabia in 2023 which involved sorting out the logistics, accomodations, brief generation for principals and direct engagement of Saudi government and private 
            entities. Aside from the above, I have also participated as a staff officer to the Minister of State during then President Halimah Yacob's state visit to Qatar in June 2023. 
    
  - title: 
    layout: list # Type of content section (list/text)
    content:
      - layout: left 
        title: Digital and Intelligence Service, Singapore Armed Forces (SAF)
        link: https://www.mindef.gov.sg/oms/dis/
        # link_text: 
        sub_title: Staff Officer at J2 (Last Held Position)
        caption: July 2015 - October 2022
        quote: >
          Watchful Vigilance against Fundamental Surprises
        description: | # this will include new lines to allow paragraphs
            I served as a Senior Military Intelligence Expert in the roles of an Analyst Officer, a Branch 2IC, and Officer Commanding in the Digital and Intelligence Service (DIS), specialising in Imagery and all-Source Intelligence. I have led a team of 20 odd soldiers for current operations and delivered routine presentations and briefs to principals to apprise them of the current intelligence situation picture.

            
            I have experience in all components of the Intelligence cycle from tasking, collection, processing, exploitation and dissemination. 
            I have also gestated and delivered on multiple capability development projects and worked with stakeholders such as DSTA and foreign vendors. 

            
            I have won several accolades during my time which included the best trainee for the Military Domain Expertise Course, Distinguished Graduate for the Tri-Service Warfighter Course and was one of the top performers under the Joint Intelligence Command.
            I have chosen to leave the SAF despite a promising career as I wanted to further challenge myself in a new area so that I can be the best that I can be.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National University of Singapore
        caption: 2011 - 2015
        sub_title: BSc of Social Sciences (Economics), Second Upper Class Honours
        quote: >
          Studied something that I was good at which was economics but my true love was always history....
        description: | # this will include new lines to allow paragraphs
          I tried Economics as a subject back in Junior College, didnt like it and opt out of it after the first three months. University Economics was different. It was a lot more mathematical and statistical. While I didnt like the whole idea of the selfish individual that underpins most of economic theory, 
          I did like playing with numbers and solving problems. While not doing calculus and solving mathematical sums, I took side modules on European History, Geopolitics, Sociology, and languages such as Bahasa Indonesia, Japanese and French.
          

          Inspired by what I discovered during my European History Module and Dan Carlin's Blueprint for Armageddon podcast, I took a semester exchange in late 2014 to Paris where i studied at Science Politique Paris. I took the time to travel on a shoe string budget such places as London, Berlin, Warsaw, Krakow, Vilnius and cities in Italy.


          I also did four years in the Guitar Ensemble of the National University of Singapore where I was Logistics Manager from 2013 to 2014 and a Section Leader in my final year. I entered not being able to sheet music and exited being able to sight read. I played in multiple concerts as part of the Ensemble and stage fright aint a fright anymore.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I like to think I am somewhat a fun person with fun hobbies. Here are some of my favourite pastime:)
      - Long Distance Cycling ( Have done long trips in Taiwan (TWICE) and Japan. Did stints in Batam and cycled around Johor)
      - Gaming (Civlization Series, XCOM, RPGs)
      - Reading (Books on European, South East Asian, Japanese History are always great, I devour Military History books and in recent times been reading up on OSINT books)
      - Travelling and visiting museums and having good food
      - Obsessesed with running a sub 10 min for my 2.4km run. (the closest I have come in the last five years was in 2020 where i clocked a 10min 17 sec.)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
